In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Data Reading

In [2]:
df=pd.read_csv("House Price India.csv")

In [3]:
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
1,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
2,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
3,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
4,6762813105,42491,3,2.50,2600,4750,1.0,0,0,4,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

Data Cleaning

In [4]:
df.columns

Index(['id', 'Date', 'number of bedrooms', 'number of bathrooms',
       'living area', 'lot area', 'number of floors', 'waterfront present',
       'number of views', 'condition of the house', 'grade of the house',
       'Area of the house(excluding basement)', 'Area of the basement',
       'Built Year', 'Renovation Year', 'Postal Code', 'Lattitude',
       'Longitude', 'living_area_renov', 'lot_area_renov',
       'Number of schools nearby', 'Distance from the airport', 'Price'],
      dtype='object')

In [5]:
df.corr()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
id,1.000000,0.045778,-0.328899,-0.516909,-0.648058,-0.100298,-0.312237,-0.112959,-0.292699,-0.044797,...,-0.068857,-0.109191,0.294579,-0.479325,-0.070978,-0.599844,-0.089646,-0.004823,-0.004633,-0.773268
Date,0.045778,1.000000,-0.015467,-0.026433,-0.021770,0.004374,-0.010230,0.011997,-0.004219,-0.027138,...,-0.006066,-0.011662,0.018064,-0.023270,-0.018359,-0.032353,-0.000082,-0.004073,0.011369,-0.027367
number of bedrooms,-0.328899,-0.015467,1.000000,0.509783,0.570441,0.034438,0.177208,-0.006247,0.078157,0.026326,...,0.153184,0.016159,-0.043978,-0.013226,0.135859,0.389765,0.029436,0.003399,-0.006066,0.308165
number of bathrooms,-0.516909,-0.026433,0.509783,1.000000,0.753540,0.080812,0.502912,0.060107,0.183780,-0.128335,...,0.498235,0.049676,-0.105504,0.031139,0.223950,0.570524,0.078637,0.002181,0.009232,0.532031
living area,-0.648058,-0.021770,0.570441,0.753540,1.000000,0.174455,0.354682,0.105858,0.287431,-0.063646,...,0.309856,0.059431,-0.080138,0.054464,0.240365,0.757540,0.180362,0.002372,0.002601,0.712276
lot area,-0.100298,0.004374,0.034438,0.080812,0.174455,1.000000,-0.004128,0.026281,0.078427,-0.008524,...,0.051602,0.006846,0.070120,-0.090978,0.221429,0.149766,0.706811,-0.012671,0.003283,0.082117
number of floors,-0.312237,-0.010230,0.177208,0.502912,0.354682,-0.004128,1.000000,0.016322,0.019860,-0.270136,...,0.481733,0.006719,-0.129704,0.050700,0.127627,0.285037,-0.010103,-0.007579,0.016617,0.262649
waterfront present,-0.112959,0.011997,-0.006247,0.060107,0.105858,0.026281,0.016322,1.000000,0.400567,0.018662,...,-0.024238,0.085863,0.038311,-0.021792,-0.047799,0.085755,0.032053,0.001563,0.001443,0.263943
number of views,-0.292699,-0.004219,0.078157,0.183780,0.287431,0.078427,0.019860,0.400567,1.000000,0.051791,...,-0.054839,0.103103,0.039834,-0.004734,-0.079411,0.281270,0.072455,0.008015,-0.001397,0.394954
condition of the house,-0.044797,-0.027138,0.026326,-0.128335,-0.063646,-0.008524,-0.270136,0.018662,0.051791,1.000000,...,-0.381554,-0.062103,0.045601,-0.003083,-0.121042,-0.099974,-0.004704,-0.006938,-0.002011,0.040609
grade of the house,-0.673374,-0.032878,0.352795,0.663082,0.761783,0.110582,0.463033,0.079853,0.254112,-0.152898,...,0.440689,0.014532,-0.146161,0.115202,0.203935,0.719983,0.116779,0.000988,0.005046,0.671805
Area of the house(excluding basement),-0.565021,-0.015781,0.473482,0.684418,0.875767,0.183596,0.525604,0.071885,0.162193,-0.168052,...,0.419679,0.025758,-0.083545,-0.000155,0.346094,0.737710,0.194730,-0.002892,0.001322,0.615179
Area of the basement,-0.290839,-0.015717,0.300367,0.287194,0.441537,0.019755,-0.242980,0.085441,0.293317,0.180650,...,-0.138861,0.075104,-0.010547,0.112992,-0.145888,0.196417,0.011283,0.010284,0.002924,0.330499
Built Year,-0.068857,-0.006066,0.153184,0.498235,0.309856,0.051602,0.481733,-0.024238,-0.054839,-0.381554,...,1.000000,-0.233732,-0.062543,-0.143108,0.414523,0.328824,0.072849,-0.001633,-0.004059,0.050936
Renovation Year,-0.109191,-0.011662,0.016159,0.049676,0.059431,0.006846,0.006719,0.085863,0.103103,-0.062103,...,-0.233732,1.000000,0.017984,0.028916,-0.080069,-0.002582,0.005865,-0.000826,0.005330,0.133362
Postal Code,0.294579,0.018064,-0.043978,-0.105504,-0.080138,0.070120,-0.129704,0.038311,0.039834,0.045601,...,-0.062543,0.017984,1.000000,-0.310145,-0.099132,-0.108332,0.077459,0.010604,0.011446,-0.115477
Lattitude,-0.479325,-0.023270,-0.013226,0.031139,0.054464,-0.090978,0.050700,-0.021792,-0.004734,-0.003083,...,-0.143108,0.028916,-0.310145,1.000000,-0.131440,0.046105,-0.091613,0.014950,0.007221,0.297570
Longitude,-0.070978,-0.018359,0.135859,0.223950,0.240365,0.221429,0.127627,-0.047799,-0.079411,-0.121042,...,0.414523,-0.080069,-0.099132,-0.131440,1.000000,0.341348,0.258056,-0.010165,-0.003158,0.024807
living_area_renov,-0.599844,-0.032353,0.389765,0.570524,0.757540,0.149766,0.285037,0.085755,0.281270,-0.099974,...,0.328824,-0.002582,-0.108332,0.046105,0.341348,1.000000,0.189261,-0.001202,-0.005605,0.585021
lot_area_renov,-0.089646,-0.000082,0.029436,0.078637,0.180362,0.706811,-0.010103,0.032053,0.072455,-0.004704,...,0.072849,0.005865,0.077459,-0.091613,0.258056,0.189261,1.000000,-0.025015,-0.014602,0.075697
Number of schools nearby,-0.004823,-0.004073,0.003399,0.002181,0.002372,-0.012671,-0.007579,0.001563,0.008015,-0.006938,...,-0.001633,-0.000826,0.010604,0.014950,-0.010165,-0.001202,-0.025015,1.000000,0.004034,0.009904
Distance from the airport,-0.004633,0.011369,-0.006066,0.009232,0.002601,0.003283,0.016617,0.001443,-0.001397,-0.002011,...,-0.004059,0.005330,0.011446,0.007221,-0.003158,-0.005605,-0.014602,0.004034,1.000000,0.004074
Price,-0.773268,-0.027367,0.308165,0.532031,0.712276,0.082117,0.262649,0.263943,0.394954,0.040609,...,0.050936,0.133362,-0.115477,0.297570,0.024807,0.585021,0.075697,0.009904,0.004074,1.000000

In [6]:
df.isnull().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14619 entries, 0 to 14618
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     14619 non-null  int64
 1   Date                                   14619 non-null  int64
 2   number of bedrooms                     14619 non-null  int64
 3   number of bathrooms                    14619 non-null  float64
 4   living area                            14619 non-null  int64
 5   lot area                               14619 non-null  int64
 6   number of floors                       14619 non-null  float64
 7   waterfront present                     14619 non-null  int64
 8   number of views                        14619 non-null  int64
 9   condition of the house                 14619 non-null  int64
 10  grade of the house                     14619 non-null  int64
 11  Area of the house(excluding basement)  14619 non-null  int64
 12  Area of the basement                   14619 non-null  int64
 13  Built Year                             14619 non-null  int64
 14  Renovation Year                        14619 non-null  int64
 15  Postal Code                            14619 non-null  int64
 16  Lattitude                              14619 non-null  float64
 17  Longitude                              14619 non-null  float64
 18  living_area_renov                      14619 non-null  int64
 19  lot_area_renov                         14619 non-null  int64
 20  Number of schools nearby               14619 non-null  int64
 21  Distance from the airport              14619 non-null  int64
 22  Price                                  14619 non-null  int64
dtypes: float64(4), int64(19)
memory usage: 2.6 MB

Feature Engineering

In [8]:
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
1,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
2,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
3,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
4,6762813105,42491,3,2.50,2600,4750,1.0,0,0,4,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [9]:
df.drop("id",axis=1,inplace=True)

In [10]:
df.head()

,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,grade of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,42491,4,2.50,2920,4000,1.5,0,0,5,8,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
1,42491,5,2.75,2910,9480,1.5,0,0,3,8,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
2,42491,4,2.50,3310,42998,2.0,0,0,3,9,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
3,42491,3,2.00,2710,4500,1.5,0,0,4,8,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
4,42491,3,2.50,2600,4750,1.0,0,0,4,9,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [11]:
df.columns

Index(['Date', 'number of bedrooms', 'number of bathrooms', 'living area',
       'lot area', 'number of floors', 'waterfront present', 'number of views',
       'condition of the house', 'grade of the house',
       'Area of the house(excluding basement)', 'Area of the basement',
       'Built Year', 'Renovation Year', 'Postal Code', 'Lattitude',
       'Longitude', 'living_area_renov', 'lot_area_renov',
       'Number of schools nearby', 'Distance from the airport', 'Price'],
      dtype='object')

In [12]:
df.drop("Date",axis=1,inplace=True)

In [13]:
df.drop("number of views",axis=1,inplace=True)

In [14]:
df.drop("waterfront present",axis=1,inplace=True)

In [15]:
df["number of bathrooms"]=np.floor(df["number of bathrooms"])
df["number of bathrooms"]=df["number of bathrooms"].astype("int")

In [16]:
df.head()

,number of bedrooms,number of bathrooms,living area,lot area,number of floors,condition of the house,grade of the house,Area of the house(excluding basement),Area of the basement,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,4,2,2920,4000,1.5,5,8,1910,1010,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
1,5,2,2910,9480,1.5,3,8,2910,0,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
2,4,2,3310,42998,2.0,3,9,3310,0,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
3,3,2,2710,4500,1.5,4,8,1880,830,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
4,3,2,2600,4750,1.0,4,9,1700,900,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [17]:
df["number of floors"]=np.floor(df["number of floors"])
df["number of floors"]=df["number of floors"].astype("int")

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14619 entries, 0 to 14618
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   number of bedrooms                     14619 non-null  int64
 1   number of bathrooms                    14619 non-null  int64
 2   living area                            14619 non-null  int64
 3   lot area                               14619 non-null  int64
 4   number of floors                       14619 non-null  int64
 5   condition of the house                 14619 non-null  int64
 6   grade of the house                     14619 non-null  int64
 7   Area of the house(excluding basement)  14619 non-null  int64
 8   Area of the basement                   14619 non-null  int64
 9   Built Year                             14619 non-null  int64
 10  Renovation Year                        14619 non-null  int64
 11  Postal Code                            14619 non-null  int64
 12  Lattitude                              14619 non-null  float64
 13  Longitude                              14619 non-null  float64
 14  living_area_renov                      14619 non-null  int64
 15  lot_area_renov                         14619 non-null  int64
 16  Number of schools nearby               14619 non-null  int64
 17  Distance from the airport              14619 non-null  int64
 18  Price                                  14619 non-null  int64
dtypes: float64(2), int64(17)
memory usage: 2.1 MB

In [19]:
df.drop(["Lattitude","Longitude"],inplace=True,axis=1)

In [20]:
df.head()

,number of bedrooms,number of bathrooms,living area,lot area,number of floors,condition of the house,grade of the house,Area of the house(excluding basement),Area of the basement,Built Year,Renovation Year,Postal Code,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,4,2,2920,4000,1,5,8,1910,1010,1909,0,122004,2470,4000,2,51,1400000
1,5,2,2910,9480,1,3,8,2910,0,1939,0,122004,2940,6600,1,53,1200000
2,4,2,3310,42998,2,3,9,3310,0,2001,0,122005,3350,42847,3,76,838000
3,3,2,2710,4500,1,4,8,1880,830,1929,0,122006,2060,4500,1,51,805000
4,3,2,2600,4750,1,4,9,1700,900,1951,0,122007,2380,4750,1,67,790000

In [21]:
df.drop("Number of schools nearby",inplace=True,axis=1)

In [22]:
df.columns

Index(['number of bedrooms', 'number of bathrooms', 'living area', 'lot area',
       'number of floors', 'condition of the house', 'grade of the house',
       'Area of the house(excluding basement)', 'Area of the basement',
       'Built Year', 'Renovation Year', 'Postal Code', 'living_area_renov',
       'lot_area_renov', 'Distance from the airport', 'Price'],
      dtype='object')

In [23]:
df.drop("Distance from the airport",axis=1,inplace=True)

In [24]:
df.head()

,number of bedrooms,number of bathrooms,living area,lot area,number of floors,condition of the house,grade of the house,Area of the house(excluding basement),Area of the basement,Built Year,Renovation Year,Postal Code,living_area_renov,lot_area_renov,Price
0,4,2,2920,4000,1,5,8,1910,1010,1909,0,122004,2470,4000,1400000
1,5,2,2910,9480,1,3,8,2910,0,1939,0,122004,2940,6600,1200000
2,4,2,3310,42998,2,3,9,3310,0,2001,0,122005,3350,42847,838000
3,3,2,2710,4500,1,4,8,1880,830,1929,0,122006,2060,4500,805000
4,3,2,2600,4750,1,4,9,1700,900,1951,0,122007,2380,4750,790000

In [25]:
df.corr()

,number of bedrooms,number of bathrooms,living area,lot area,number of floors,condition of the house,grade of the house,Area of the house(excluding basement),Area of the basement,Built Year,Renovation Year,Postal Code,living_area_renov,lot_area_renov,Price
number of bedrooms,1.000000,0.459614,0.570441,0.034438,0.158713,0.026326,0.352795,0.473482,0.300367,0.153184,0.016159,-0.043978,0.389765,0.029436,0.308165
number of bathrooms,0.459614,1.000000,0.697667,0.077588,0.485487,-0.128175,0.605604,0.639676,0.254736,0.427656,0.059654,-0.083225,0.511781,0.071139,0.514371
living area,0.570441,0.697667,1.000000,0.174455,0.352843,-0.063646,0.761783,0.875767,0.441537,0.309856,0.059431,-0.080138,0.757540,0.180362,0.712276
lot area,0.034438,0.077588,0.174455,1.000000,-0.009218,-0.008524,0.110582,0.183596,0.019755,0.051602,0.006846,0.070120,0.149766,0.706811,0.082117
number of floors,0.158713,0.485487,0.352843,-0.009218,1.000000,-0.303070,0.475837,0.520085,-0.236527,0.572249,-0.007020,-0.124269,0.300967,-0.011870,0.241395
condition of the house,0.026326,-0.128175,-0.063646,-0.008524,-0.303070,1.000000,-0.152898,-0.168052,0.180650,-0.381554,-0.062103,0.045601,-0.099974,-0.004704,0.040609
grade of the house,0.352795,0.605604,0.761783,0.110582,0.475837,-0.152898,1.000000,0.758161,0.167187,0.440689,0.014532,-0.146161,0.719983,0.116779,0.671805
Area of the house(excluding basement),0.473482,0.639676,0.875767,0.183596,0.520085,-0.168052,0.758161,1.000000,-0.046446,0.419679,0.025758,-0.083545,0.737710,0.194730,0.615179
Area of the basement,0.300367,0.254736,0.441537,0.019755,-0.236527,0.180650,0.167187,-0.046446,1.000000,-0.138861,0.075104,-0.010547,0.196417,0.011283,0.330499
Built Year,0.153184,0.427656,0.309856,0.051602,0.572249,-0.381554,0.440689,0.419679,-0.138861,1.000000,-0.233732,-0.062543,0.328824,0.072849,0.050936
Renovation Year,0.016159,0.059654,0.059431,0.006846,-0.007020,-0.062103,0.014532,0.025758,0.075104,-0.233732,1.000000,0.017984,-0.002582,0.005865,0.133362
Postal Code,-0.043978,-0.083225,-0.080138,0.070120,-0.124269,0.045601,-0.146161,-0.083545,-0.010547,-0.062543,0.017984,1.000000,-0.108332,0.077459,-0.115477
living_area_renov,0.389765,0.511781,0.757540,0.149766,0.300967,-0.099974,0.719983,0.737710,0.196417,0.328824,-0.002582,-0.108332,1.000000,0.189261,0.585021
lot_area_renov,0.029436,0.071139,0.180362,0.706811,-0.011870,-0.004704,0.116779,0.194730,0.011283,0.072849,0.005865,0.077459,0.189261,1.000000,0.075697
Price,0.308165,0.514371,0.712276,0.082117,0.241395,0.040609,0.671805,0.615179,0.330499,0.050936,0.133362,-0.115477,0.585021,0.075697,1.000000

In [26]:
df.drop("condition of the house",inplace=True,axis=1)

In [27]:
df.drop(["lot_area_renov","Built Year","lot area"],axis=1,inplace=True)

In [28]:
df.head()

,number of bedrooms,number of bathrooms,living area,number of floors,grade of the house,Area of the house(excluding basement),Area of the basement,Renovation Year,Postal Code,living_area_renov,Price
0,4,2,2920,1,8,1910,1010,0,122004,2470,1400000
1,5,2,2910,1,8,2910,0,0,122004,2940,1200000
2,4,2,3310,2,9,3310,0,0,122005,3350,838000
3,3,2,2710,1,8,1880,830,0,122006,2060,805000
4,3,2,2600,1,9,1700,900,0,122007,2380,790000

In [29]:
df.corr()

,number of bedrooms,number of bathrooms,living area,number of floors,grade of the house,Area of the house(excluding basement),Area of the basement,Renovation Year,Postal Code,living_area_renov,Price
number of bedrooms,1.000000,0.459614,0.570441,0.158713,0.352795,0.473482,0.300367,0.016159,-0.043978,0.389765,0.308165
number of bathrooms,0.459614,1.000000,0.697667,0.485487,0.605604,0.639676,0.254736,0.059654,-0.083225,0.511781,0.514371
living area,0.570441,0.697667,1.000000,0.352843,0.761783,0.875767,0.441537,0.059431,-0.080138,0.757540,0.712276
number of floors,0.158713,0.485487,0.352843,1.000000,0.475837,0.520085,-0.236527,-0.007020,-0.124269,0.300967,0.241395
grade of the house,0.352795,0.605604,0.761783,0.475837,1.000000,0.758161,0.167187,0.014532,-0.146161,0.719983,0.671805
Area of the house(excluding basement),0.473482,0.639676,0.875767,0.520085,0.758161,1.000000,-0.046446,0.025758,-0.083545,0.737710,0.615179
Area of the basement,0.300367,0.254736,0.441537,-0.236527,0.167187,-0.046446,1.000000,0.075104,-0.010547,0.196417,0.330499
Renovation Year,0.016159,0.059654,0.059431,-0.007020,0.014532,0.025758,0.075104,1.000000,0.017984,-0.002582,0.133362
Postal Code,-0.043978,-0.083225,-0.080138,-0.124269,-0.146161,-0.083545,-0.010547,0.017984,1.000000,-0.108332,-0.115477
living_area_renov,0.389765,0.511781,0.757540,0.300967,0.719983,0.737710,0.196417,-0.002582,-0.108332,1.000000,0.585021
Price,0.308165,0.514371,0.712276,0.241395,0.671805,0.615179,0.330499,0.133362,-0.115477,0.585021,1.000000

Ddependent and Independent Features

In [30]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [31]:
X.head()

,number of bedrooms,number of bathrooms,living area,number of floors,grade of the house,Area of the house(excluding basement),Area of the basement,Renovation Year,Postal Code,living_area_renov
0,4,2,2920,1,8,1910,1010,0,122004,2470
1,5,2,2910,1,8,2910,0,0,122004,2940
2,4,2,3310,2,9,3310,0,0,122005,3350
3,3,2,2710,1,8,1880,830,0,122006,2060
4,3,2,2600,1,9,1700,900,0,122007,2380

In [32]:
y

0        1400000
1        1200000
2         838000
3         805000
4         790000
          ...
14614     221700
14615     219200
14616     209000
14617     205000
14618     146000
Name: Price, Length: 14619, dtype: int64

Train Test Split

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=10)

In [35]:
X_train.shape,X_test.shape

((10233, 10), (4386, 10))

Standardization

In [36]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()

In [37]:
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [38]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9
0,0.643530,3.030357,3.434355,0.981898,2.792213,4.165277,-0.662665,-0.22329,-0.675046,3.788158
1,-1.444371,-1.034171,-0.858322,0.981898,-0.579796,-0.602153,-0.662665,-0.22329,-1.512380,-0.943052
2,0.643530,0.320671,0.145438,0.981898,1.106209,0.512619,-0.662665,-0.22329,-0.779713,0.336819
3,0.643530,0.320671,0.198830,0.981898,1.106209,0.571916,-0.662665,-0.22329,-0.727379,0.480625
4,-0.400421,0.320671,-0.730183,0.981898,0.263206,-0.791901,-0.035930,-0.22329,-0.884379,-0.957433
...,...,...,...,...,...,...,...,...,...,...
10228,0.643530,0.320671,1.181233,0.981898,1.949211,1.662969,-0.662665,-0.22329,-0.675046,2.493906
10229,-0.400421,0.320671,-0.505938,-0.824279,1.106209,-0.210797,-0.662665,-0.22329,1.051956,0.351200
10230,0.643530,0.320671,0.487144,0.981898,0.263206,0.892116,-0.662665,-0.22329,1.575289,0.796998
10231,-0.400421,0.320671,-0.488853,0.981898,-0.579796,-0.191822,-0.662665,-0.22329,-0.465712,-0.044266
10232,0.643530,0.320671,-0.132198,0.981898,-0.579796,0.204278,-0.662665,-0.22329,-0.779713,-0.037076

In [39]:
pd.DataFrame(X_test)

,0,1,2,3,4,5,6,7,8,9
0,0.643530,0.320671,0.775458,0.981898,1.949211,1.212317,-0.662665,-0.22329,-0.675046,2.637712
1,-0.400421,-1.034171,-1.050532,-0.824279,-0.579796,-0.815620,-0.662665,-0.22329,0.109955,-0.454112
2,-0.400421,-1.034171,-1.103923,-0.824279,-1.422798,-0.874916,-0.662665,-0.22329,0.057621,-1.417611
3,-1.444371,-1.034171,-1.499020,-0.824279,-3.108802,-1.313709,-0.662665,-0.22329,1.784623,-0.583538
4,-0.400421,-1.034171,-0.548651,-0.824279,-0.579796,-0.851198,0.456505,-0.22329,0.371622,-0.080217
...,...,...,...,...,...,...,...,...,...,...
4381,-0.400421,-1.034171,-0.548651,-0.824279,-0.579796,-0.258234,-0.662665,-0.22329,-0.099379,-1.230664
4382,0.643530,4.385199,5.313736,0.981898,3.635215,4.687085,2.291943,-0.22329,1.993957,1.631071
4383,0.643530,0.320671,0.252221,0.981898,1.106209,0.631212,-0.662665,-0.22329,-1.146046,0.725095
4384,-0.400421,0.320671,0.348326,-0.824279,0.263206,-0.637731,1.933809,-0.22329,-0.884379,0.725095
4385,-0.400421,-1.034171,-1.221384,-0.824279,-0.579796,-1.005368,-0.662665,-0.22329,0.947289,-0.784866

Model Training

In [40]:
from sklearn.linear_model import LinearRegression
linear=LinearRegression()

In [41]:
linear.fit(X_train,y_train)

LinearRegression()

In [42]:
linear.intercept_

np.float64(541758.8333821937)

In [43]:
linear.coef_

array([-43426.36268645,  11889.01756648, 102832.7919424 , -31474.2695161 ,
       120259.6526739 ,  81786.83329436,  61187.84917714,  36693.35483337,
       -12969.7687696 ,   2483.06083156])

In [44]:
y_pred=linear.predict(X_test)

In [45]:
y_pred

array([866590.58005855, 277039.8998955 , 163607.0196526 , ...,
       665238.45398502, 727621.19414575, 232270.3926896 ])

Model Evaluation and Performance Metrics

In [46]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [47]:
score=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [48]:
print("Accuracy : ",score)
print("Mean Absoulute Error : ",mae)
print("Mean Squared Error : ",mse)
print("Root Mean Squared Error : ",rmse)

Accuracy :  0.5808179526378234
Mean Absoulute Error :  151545.99544370963
Mean Squared Error :  47941293658.617874
Root Mean Squared Error :  218955.0037304877

In [49]:
sum(df["Price"])/len(df["Price"])

538806.2816882139

Training Multiple Models

In [50]:
#Linear, Ridge, Lasso,  SVR, Adaboost, Gradient boost, XGboost, KNN, Decision Tree, Random Forest
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.svm import SVR
from sklearn.ensemble import AdaBoostRegressor,GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.pipeline import Pipeline

In [51]:
#Train test splitting the data and proceeding with out scaling
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=10)

In [52]:
'''
Tree based models like decision tree,random forest,gradient boost,XGboost,Adaboost doesn't need scaled or standardized data
Distance based models like knn,kmeans and gradient based models like Linear,Ridge,Lasso needs scaled data
With out scaling the data, split it into training and testing
For scaling required models, use pipeline method in scikit-learn to apply preprocessing and model in same step
'''

models={
    'Linear Regression':Pipeline([
                                ("scalar",StandardScaler()),
                                ("model",LinearRegression())
                                ]),
    'Ridge':Pipeline([
                    ("scalar",StandardScaler()),
                    ("model",Ridge(alpha=1.0))
                    ]),
    'Lasso':Pipeline([
                    ("scalar",StandardScaler()),
                    ("model",Lasso(alpha=0.1))
                    ]),
    'Elastic Net':Pipeline([
                            ("scalar",StandardScaler()),
                            ("model",ElasticNet(alpha=1.0))
                            ]),
    'Support Vector Regressor':Pipeline([
                                ("scalar",StandardScaler()),
                                ("model",SVR(C=100,gamma=0.1,kernel="rbf"))
                                ]),
    'KNN':Pipeline([
                    ("scalar",StandardScaler()),
                    ("model",KNeighborsRegressor(n_neighbors=5))
                    ]),
    'DecisionTree':DecisionTreeRegressor(max_depth=10),
    'Random Forest':RandomForestRegressor(n_estimators=100),
    'Adaboost':AdaBoostRegressor(n_estimators=100),
    'Gradient Boost':GradientBoostingRegressor(n_estimators=100),
    'XG boost':XGBRegressor(n_estimators=100,learning_rate=0.1)
}

In [53]:
#Function for evaluating the model
def evaluate_model(y_true,y_pred):
    from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,root_mean_squared_error
    mse=mean_squared_error(y_true,y_pred)
    mae=mean_absolute_error(y_true,y_pred)
    rmse=root_mean_squared_error(y_true,y_pred)
    score=r2_score(y_true,y_pred)
    return mse,mae,rmse,score

In [153]:
#Model Building, Training and Evaluation
for name,model in models.items():
    mo=model

    #Training the model
    mo.fit(X_train,y_train)

    #Evaluating the model
    y_train_pred=mo.predict(X_train)
    mse1,mae1,rmse1,score1=evaluate_model(y_train,y_train_pred)
    y_test_pred=mo.predict(X_test)
    mse2,mae2,rmse2,score2=evaluate_model(y_test,y_test_pred)

    #Printing the model metrics
    print("="*30)
    print("Model : "+name)
    print("-"*30)
    print("Training Data :")
    print("Accuracy : ",score1)
    print("Mean Squared Error : ",mse1)
    print("Mean Absolute Error : ",mae1)
    print("Root Mean Squared Error : ",rmse1)
    print("-"*30)
    print("Testing Data :")
    print("Accuracy : ",score2)
    print("Mean Squared Error : ",mse2)
    print("Mean Absolute Error : ",mae2)
    print("Root Mean Squared Error : ",rmse2)
    print("="*30)
    print("\n\n\n")

==============================
Model : Linear Regression
------------------------------
Training Data :
Accuracy :  0.5737191662681922
Mean Squared Error :  61212610332.15046
Mean Absolute Error :  157063.21410017164
Root Mean Squared Error :  247411.82334753216
------------------------------
Testing Data :
Accuracy :  0.5808179526378234
Mean Squared Error :  47941293658.617874
Mean Absolute Error :  151545.99544370963
Root Mean Squared Error :  218955.0037304877
==============================




==============================
Model : Ridge
------------------------------
Training Data :
Accuracy :  0.5737191617897052
Mean Squared Error :  61212610975.24736
Mean Absolute Error :  157060.69297627822
Root Mean Squared Error :  247411.82464718085
------------------------------
Testing Data :
Accuracy :  0.5808235171429911
Mean Squared Error :  47940657253.557144
Mean Absolute Error :  151543.78070881983
Root Mean Squared Error :  218953.55044747994
==============================

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.490e+13, tolerance: 1.469e+11
  model = cd_fast.enet_coordinate_descent(

==============================
Model : Lasso
------------------------------
Training Data :
Accuracy :  0.573719166266013
Mean Squared Error :  61212610332.46338
Mean Absolute Error :  157063.23097999344
Root Mean Squared Error :  247411.82334816456
------------------------------
Testing Data :
Accuracy :  0.5808178412551963
Mean Squared Error :  47941306397.300896
Mean Absolute Error :  151546.01887066988
Root Mean Squared Error :  218955.0328202138
==============================




==============================
Model : Elastic Net
------------------------------
Training Data :
Accuracy :  0.5492773822715118
Mean Squared Error :  64722374978.41339
Mean Absolute Error :  154418.39570726495
Root Mean Squared Error :  254405.92559610988
------------------------------
Testing Data :
Accuracy :  0.568630673091693
Mean Squared Error :  49335136623.26156
Mean Absolute Error :  148706.43054607668
Root Mean Squared Error :  222115.1427149026
==============================




==============================
Model : Support Vector Regressor
------------------------------
Training Data :
Accuracy :  0.07447939725784958
Mean Squared Error :  132901898295.70319
Mean Absolute Error :  196949.9853370792
Root Mean Squared Error :  364557.12624457525
------------------------------
Testing Data :
Accuracy :  0.09735441659053501
Mean Squared Error :  103234375747.24792
Mean Absolute Error :  186718.2217360282
Root Mean Squared Error :  321301.067143027
==============================




==============================
Model : KNN
------------------------------
Training Data :
Accuracy :  0.7495602598828399
Mean Squared Error :  35962372713.95031
Mean Absolute Error :  109162.2341835239
Root Mean Squared Error :  189637.47708180023
------------------------------
Testing Data :
Accuracy :  0.6704927107002807
Mean Squared Error :  37685310757.89192
Mean Absolute Error :  123792.78016415867
Root Mean Squared Error :  194127.04798119175
==============================




==============================
Model : DecisionTree
------------------------------
Training Data :
Accuracy :  0.8636513840089909
Mean Squared Error :  19579239880.244434
Mean Absolute Error :  93445.10492088512
Root Mean Squared Error :  139925.83707180183
------------------------------
Testing Data :
Accuracy :  0.6056811809334214
Mean Squared Error :  45097719281.992325
Mean Absolute Error :  121461.22493841685
Root Mean Squared Error :  212362.2360072344
==============================




==============================
Model : Random Forest
------------------------------
Training Data :
Accuracy :  0.9661063447747656
Mean Squared Error :  4867024144.322251
Mean Absolute Error :  35729.163396018404
Root Mean Squared Error :  69764.06054927029
------------------------------
Testing Data :
Accuracy :  0.7899948345657563
Mean Squared Error :  24018011671.217747
Mean Absolute Error :  89782.91846113263
Root Mean Squared Error :  154977.4553643779
==============================




==============================
Model : Adaboost
------------------------------
Training Data :
Accuracy :  0.29018891321276286
Mean Squared Error :  101926678440.07109
Mean Absolute Error :  266464.2722638821
Root Mean Squared Error :  319259.578462528
------------------------------
Testing Data :
Accuracy :  0.13608307307635714
Mean Squared Error :  98805030775.83427
Mean Absolute Error :  261691.58021365677
Root Mean Squared Error :  314332.67532319046
==============================




==============================
Model : Gradient Boost
------------------------------
Training Data :
Accuracy :  0.8347597110313892
Mean Squared Error :  23727994832.090374
Mean Absolute Error :  97711.8161187208
Root Mean Squared Error :  154038.93933707275
------------------------------
Testing Data :
Accuracy :  0.7780046977236156
Mean Squared Error :  25389307686.811245
Mean Absolute Error :  100336.95753319889
Root Mean Squared Error :  159340.22620421764
==============================




==============================
Model : XG boost
------------------------------
Training Data :
Accuracy :  0.9234814047813416
Mean Squared Error :  10987832320.0
Mean Absolute Error :  68370.7109375
Root Mean Squared Error :  104822.859375
------------------------------
Testing Data :
Accuracy :  0.8041069507598877
Mean Squared Error :  22404026368.0
Mean Absolute Error :  85068.078125
Root Mean Squared Error :  149679.75
==============================

The Best performing models are Random Forest, Gradient Boost and XG Boost.
Applying Hyperparameter tuning for the best performing models to get better accuracy.

Hyperparameter Tuning

In [154]:
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

gradient_params={"loss": ['squared_error','huber','absolute_error'],
             "criterion": ['friedman_mse','squared_error','mse'],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500],
              "max_depth": [5, 8, 15, None, 10],
            }

xgboost_params = {"learning_rate": [0.1, 0.01],
                  "max_depth": [5, 8, 12, 20, 30],
                  "n_estimators": [100, 200, 300],
                  "colsample_bytree": [0.5, 0.8, 1, 0.3, 0.4]}

In [156]:
grid_search_models=[
    ("Random Forest",RandomForestRegressor(),rf_params),
    ("Gradient Boosting",GradientBoostingRegressor(),gradient_params),
    ("XG Boosting",XGBRegressor(),xgboost_params)
]

In [160]:
import warnings
warnings.filterwarnings("ignore")


from sklearn.model_selection import RandomizedSearchCV


best_params={}
for name,model,params in grid_search_models:
    model=RandomizedSearchCV(estimator=model,
                             param_distributions=params,
                             cv=5,
                             n_iter=100,
                             n_jobs=-1,
                             verbose=2)

    model.fit(X_train,y_train)

    best_params[name]=model.best_params_


for model in best_params:
    print(f"------------------Best params for {model}--------------------------------")
    print(best_params[model])

Fitting 5 folds for each of 100 candidates, totalling 500 fits
Fitting 5 folds for each of 100 candidates, totalling 500 fits
Fitting 5 folds for each of 100 candidates, totalling 500 fits
------------------Best params for Random Forest--------------------------------
{'n_estimators': 100, 'min_samples_split': 8, 'max_features': 8, 'max_depth': None}
------------------Best params for Gradient Boosting--------------------------------
{'n_estimators': 200, 'min_samples_split': 8, 'max_depth': 5, 'loss': 'huber', 'criterion': 'squared_error'}
------------------Best params for XG Boosting--------------------------------
{'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.1, 'colsample_bytree': 0.5}

In [163]:
model.feature_importances_

array([0.01925283, 0.03201952, 0.23078494, 0.0183235 , 0.413957  ,
       0.03364665, 0.04986547, 0.05459487, 0.1111796 , 0.03637563],
      dtype=float32)

In [54]:
#Training the models using the best parameter
model1=RandomForestRegressor(n_estimators=100,min_samples_split=8,max_features=8)
model2=GradientBoostingRegressor(n_estimators=200,min_samples_split=8,max_depth=5,loss="huber",criterion="squared_error")
model3=XGBRegressor(n_estimators=300,max_depth=5,learning_rate=0.1,colsample_bytree=0.5)

models={
    "Random Forest" : model1,
    "Gradient Boosting" : model2,
    "XG Boosting" : model3
}

In [55]:
#Model Building, Training and Evaluation
for name,model in models.items():
    mo=model

    #Training the model
    mo.fit(X_train,y_train)

    #Evaluating the model
    y_train_pred=mo.predict(X_train)
    mse1,mae1,rmse1,score1=evaluate_model(y_train,y_train_pred)
    y_test_pred=mo.predict(X_test)
    mse2,mae2,rmse2,score2=evaluate_model(y_test,y_test_pred)

    #Printing the model metrics
    print("="*30)
    print("Model : "+name)
    print("-"*30)
    print("Training Data :")
    print("Accuracy : ",score1)
    print("Mean Squared Error : ",mse1)
    print("Mean Absolute Error : ",mae1)
    print("Root Mean Squared Error : ",rmse1)
    print("-"*30)
    print("Testing Data :")
    print("Accuracy : ",score2)
    print("Mean Squared Error : ",mse2)
    print("Mean Absolute Error : ",mae2)
    print("Root Mean Squared Error : ",rmse2)
    print("="*30)
    print("\n\n\n")

==============================
Model : Random Forest
------------------------------
Training Data :
Accuracy :  0.9176941015448328
Mean Squared Error :  11818872657.416788
Mean Absolute Error :  55304.72562825728
Root Mean Squared Error :  108714.6386528364
------------------------------
Testing Data :
Accuracy :  0.7855754958997054
Mean Squared Error :  24523445561.0975
Mean Absolute Error :  91713.14345230914
Root Mean Squared Error :  156599.6346135504
==============================




==============================
Model : Gradient Boosting
------------------------------
Training Data :
Accuracy :  0.8967291524719305
Mean Squared Error :  14829374553.545527
Mean Absolute Error :  66851.41003157731
Root Mean Squared Error :  121775.91943215016
------------------------------
Testing Data :
Accuracy :  0.8409787693527704
Mean Squared Error :  18187046807.915215
Mean Absolute Error :  79259.1762316958
Root Mean Squared Error :  134859.3593634317
==============================




==============================
Model : XG Boosting
------------------------------
Training Data :
Accuracy :  0.9381009936332703
Mean Squared Error :  8888506368.0
Mean Absolute Error :  61667.6875
Root Mean Squared Error :  94278.875
------------------------------
Testing Data :
Accuracy :  0.8285865187644958
Mean Squared Error :  19604334592.0
Mean Absolute Error :  80881.5078125
Root Mean Squared Error :  140015.484375
==============================

Therefore, Gradient Boosting is the best algorithm for this dataset.

Eliminating Featues that has less correlation to the Price of the house. (<0.1)
Training the models once again with the new features.

In [56]:
df=pd.read_csv("House Price India.csv")

In [57]:
df.head()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
1,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
2,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
3,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
4,6762813105,42491,3,2.50,2600,4750,1.0,0,0,4,...,1951,0,122007,52.9133,-114.590,2380,4750,1,67,790000

In [58]:
df.corr()

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
id,1.000000,0.045778,-0.328899,-0.516909,-0.648058,-0.100298,-0.312237,-0.112959,-0.292699,-0.044797,...,-0.068857,-0.109191,0.294579,-0.479325,-0.070978,-0.599844,-0.089646,-0.004823,-0.004633,-0.773268
Date,0.045778,1.000000,-0.015467,-0.026433,-0.021770,0.004374,-0.010230,0.011997,-0.004219,-0.027138,...,-0.006066,-0.011662,0.018064,-0.023270,-0.018359,-0.032353,-0.000082,-0.004073,0.011369,-0.027367
number of bedrooms,-0.328899,-0.015467,1.000000,0.509783,0.570441,0.034438,0.177208,-0.006247,0.078157,0.026326,...,0.153184,0.016159,-0.043978,-0.013226,0.135859,0.389765,0.029436,0.003399,-0.006066,0.308165
number of bathrooms,-0.516909,-0.026433,0.509783,1.000000,0.753540,0.080812,0.502912,0.060107,0.183780,-0.128335,...,0.498235,0.049676,-0.105504,0.031139,0.223950,0.570524,0.078637,0.002181,0.009232,0.532031
living area,-0.648058,-0.021770,0.570441,0.753540,1.000000,0.174455,0.354682,0.105858,0.287431,-0.063646,...,0.309856,0.059431,-0.080138,0.054464,0.240365,0.757540,0.180362,0.002372,0.002601,0.712276
lot area,-0.100298,0.004374,0.034438,0.080812,0.174455,1.000000,-0.004128,0.026281,0.078427,-0.008524,...,0.051602,0.006846,0.070120,-0.090978,0.221429,0.149766,0.706811,-0.012671,0.003283,0.082117
number of floors,-0.312237,-0.010230,0.177208,0.502912,0.354682,-0.004128,1.000000,0.016322,0.019860,-0.270136,...,0.481733,0.006719,-0.129704,0.050700,0.127627,0.285037,-0.010103,-0.007579,0.016617,0.262649
waterfront present,-0.112959,0.011997,-0.006247,0.060107,0.105858,0.026281,0.016322,1.000000,0.400567,0.018662,...,-0.024238,0.085863,0.038311,-0.021792,-0.047799,0.085755,0.032053,0.001563,0.001443,0.263943
number of views,-0.292699,-0.004219,0.078157,0.183780,0.287431,0.078427,0.019860,0.400567,1.000000,0.051791,...,-0.054839,0.103103,0.039834,-0.004734,-0.079411,0.281270,0.072455,0.008015,-0.001397,0.394954
condition of the house,-0.044797,-0.027138,0.026326,-0.128335,-0.063646,-0.008524,-0.270136,0.018662,0.051791,1.000000,...,-0.381554,-0.062103,0.045601,-0.003083,-0.121042,-0.099974,-0.004704,-0.006938,-0.002011,0.040609
grade of the house,-0.673374,-0.032878,0.352795,0.663082,0.761783,0.110582,0.463033,0.079853,0.254112,-0.152898,...,0.440689,0.014532,-0.146161,0.115202,0.203935,0.719983,0.116779,0.000988,0.005046,0.671805
Area of the house(excluding basement),-0.565021,-0.015781,0.473482,0.684418,0.875767,0.183596,0.525604,0.071885,0.162193,-0.168052,...,0.419679,0.025758,-0.083545,-0.000155,0.346094,0.737710,0.194730,-0.002892,0.001322,0.615179
Area of the basement,-0.290839,-0.015717,0.300367,0.287194,0.441537,0.019755,-0.242980,0.085441,0.293317,0.180650,...,-0.138861,0.075104,-0.010547,0.112992,-0.145888,0.196417,0.011283,0.010284,0.002924,0.330499
Built Year,-0.068857,-0.006066,0.153184,0.498235,0.309856,0.051602,0.481733,-0.024238,-0.054839,-0.381554,...,1.000000,-0.233732,-0.062543,-0.143108,0.414523,0.328824,0.072849,-0.001633,-0.004059,0.050936
Renovation Year,-0.109191,-0.011662,0.016159,0.049676,0.059431,0.006846,0.006719,0.085863,0.103103,-0.062103,...,-0.233732,1.000000,0.017984,0.028916,-0.080069,-0.002582,0.005865,-0.000826,0.005330,0.133362
Postal Code,0.294579,0.018064,-0.043978,-0.105504,-0.080138,0.070120,-0.129704,0.038311,0.039834,0.045601,...,-0.062543,0.017984,1.000000,-0.310145,-0.099132,-0.108332,0.077459,0.010604,0.011446,-0.115477
Lattitude,-0.479325,-0.023270,-0.013226,0.031139,0.054464,-0.090978,0.050700,-0.021792,-0.004734,-0.003083,...,-0.143108,0.028916,-0.310145,1.000000,-0.131440,0.046105,-0.091613,0.014950,0.007221,0.297570
Longitude,-0.070978,-0.018359,0.135859,0.223950,0.240365,0.221429,0.127627,-0.047799,-0.079411,-0.121042,...,0.414523,-0.080069,-0.099132,-0.131440,1.000000,0.341348,0.258056,-0.010165,-0.003158,0.024807
living_area_renov,-0.599844,-0.032353,0.389765,0.570524,0.757540,0.149766,0.285037,0.085755,0.281270,-0.099974,...,0.328824,-0.002582,-0.108332,0.046105,0.341348,1.000000,0.189261,-0.001202,-0.005605,0.585021
lot_area_renov,-0.089646,-0.000082,0.029436,0.078637,0.180362,0.706811,-0.010103,0.032053,0.072455,-0.004704,...,0.072849,0.005865,0.077459,-0.091613,0.258056,0.189261,1.000000,-0.025015,-0.014602,0.075697
Number of schools nearby,-0.004823,-0.004073,0.003399,0.002181,0.002372,-0.012671,-0.007579,0.001563,0.008015,-0.006938,...,-0.001633,-0.000826,0.010604,0.014950,-0.010165,-0.001202,-0.025015,1.000000,0.004034,0.009904
Distance from the airport,-0.004633,0.011369,-0.006066,0.009232,0.002601,0.003283,0.016617,0.001443,-0.001397,-0.002011,...,-0.004059,0.005330,0.011446,0.007221,-0.003158,-0.005605,-0.014602,0.004034,1.000000,0.004074
Price,-0.773268,-0.027367,0.308165,0.532031,0.712276,0.082117,0.262649,0.263943,0.394954,0.040609,...,0.050936,0.133362,-0.115477,0.297570,0.024807,0.585021,0.075697,0.009904,0.004074,1.000000

In [59]:
lst=["id","Date","lot area","condition of the house","Built Year","Lattitude","Longitude","lot_area_renov","Number of schools nearby","Distance from the airport"]

In [60]:
df.drop(lst,axis=1,inplace=True)

In [61]:
df.head()

,number of bedrooms,number of bathrooms,living area,number of floors,waterfront present,number of views,grade of the house,Area of the house(excluding basement),Area of the basement,Renovation Year,Postal Code,living_area_renov,Price
0,4,2.50,2920,1.5,0,0,8,1910,1010,0,122004,2470,1400000
1,5,2.75,2910,1.5,0,0,8,2910,0,0,122004,2940,1200000
2,4,2.50,3310,2.0,0,0,9,3310,0,0,122005,3350,838000
3,3,2.00,2710,1.5,0,0,8,1880,830,0,122006,2060,805000
4,3,2.50,2600,1.0,0,0,9,1700,900,0,122007,2380,790000

In [76]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [77]:
#Train test splitting the data and proceeding with out scaling
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=10)

In [80]:
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [81]:
models={
    'Random Forest':RandomForestRegressor(n_estimators=100),
    'Gradient Boost':GradientBoostingRegressor(n_estimators=100),
    'XG boost':XGBRegressor(n_estimators=100,learning_rate=0.1) 
}

In [82]:
#Model Building, Training and Evaluation
for name,model in models.items():
    mo=model

    #Training the model
    mo.fit(X_train,y_train)

    #Evaluating the model
    y_train_pred=mo.predict(X_train)
    mse1,mae1,rmse1,score1=evaluate_model(y_train,y_train_pred)
    y_test_pred=mo.predict(X_test)
    mse2,mae2,rmse2,score2=evaluate_model(y_test,y_test_pred)

    #Printing the model metrics
    print("="*30)
    print("Model : "+name)
    print("-"*30)
    print("Training Data :")
    print("Accuracy : ",score1)
    print("Mean Squared Error : ",mse1)
    print("Mean Absolute Error : ",mae1)
    print("Root Mean Squared Error : ",rmse1)
    print("-"*30)
    print("Testing Data :")
    print("Accuracy : ",score2)
    print("Mean Squared Error : ",mse2)
    print("Mean Absolute Error : ",mae2)
    print("Root Mean Squared Error : ",rmse2)
    print("="*30)
    print("\n\n\n")

==============================
Model : Random Forest
------------------------------
Training Data :
Accuracy :  0.9715527379123126
Mean Squared Error :  4084938921.475687
Mean Absolute Error :  33401.48413427472
Root Mean Squared Error :  63913.526905309234
------------------------------
Testing Data :
Accuracy :  0.8168342812904804
Mean Squared Error :  20948419819.272102
Mean Absolute Error :  85419.0533750163
Root Mean Squared Error :  144735.6895146187
==============================




==============================
Model : Gradient Boost
------------------------------
Training Data :
Accuracy :  0.8712663679318137
Mean Squared Error :  18485751722.513645
Mean Absolute Error :  91555.9037407485
Root Mean Squared Error :  135962.3172887019
------------------------------
Testing Data :
Accuracy :  0.8128579335411096
Mean Squared Error :  21403189426.75165
Mean Absolute Error :  95147.61736090494
Root Mean Squared Error :  146298.2892133454
==============================




==============================
Model : XG boost
------------------------------
Training Data :
Accuracy :  0.9414740800857544
Mean Squared Error :  8404144128.0
Mean Absolute Error :  63515.1640625
Root Mean Squared Error :  91674.1171875
------------------------------
Testing Data :
Accuracy :  0.8562796711921692
Mean Squared Error :  16437100544.0
Mean Absolute Error :  78635.3359375
Root Mean Squared Error :  128207.2578125
==============================

Hyperparameter Tuning

In [83]:
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

gradient_params={"loss": ['squared_error','huber','absolute_error'],
             "criterion": ['friedman_mse','squared_error','mse'],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500],
              "max_depth": [5, 8, 15, None, 10],
            }

xgboost_params = {"learning_rate": [0.1, 0.01],
                  "max_depth": [5, 8, 12, 20, 30],
                  "n_estimators": [100, 200, 300],
                  "colsample_bytree": [0.5, 0.8, 1, 0.3, 0.4]}

In [84]:
grid_search_models=[
    ("Random Forest",RandomForestRegressor(),rf_params),
    ("Gradient Boosting",GradientBoostingRegressor(),gradient_params),
    ("XG Boosting",XGBRegressor(),xgboost_params)
]

In [190]:
import warnings
warnings.filterwarnings("ignore")


from sklearn.model_selection import RandomizedSearchCV


best_params={}
for name,model,params in grid_search_models:
    model=RandomizedSearchCV(estimator=model,
                             param_distributions=params,
                             cv=5,
                             n_iter=100,
                             n_jobs=-1,
                             verbose=2)

    model.fit(X_train,y_train) 

    best_params[name]=model.best_params_


for model in best_params:
    print(f"------------------Best params for {model}--------------------------------")
    print(best_params[model])

Fitting 5 folds for each of 100 candidates, totalling 500 fits
Fitting 5 folds for each of 100 candidates, totalling 500 fits
Fitting 5 folds for each of 100 candidates, totalling 500 fits
------------------Best params for Random Forest--------------------------------
{'n_estimators': 100, 'min_samples_split': 8, 'max_features': 8, 'max_depth': None}
------------------Best params for Gradient Boosting--------------------------------
{'n_estimators': 500, 'min_samples_split': 15, 'max_depth': 5, 'loss': 'squared_error', 'criterion': 'friedman_mse'}
------------------Best params for XG Boosting--------------------------------
{'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.1, 'colsample_bytree': 0.5}

In [85]:
#Training the models using the best parameter
model1=RandomForestRegressor(n_estimators=100,min_samples_split=8,max_features=8)
model2=GradientBoostingRegressor(n_estimators=500,min_samples_split=15,max_depth=5,loss="squared_error",criterion="friedman_mse")
model3=XGBRegressor(n_estimators=200,max_depth=5,learning_rate=0.1,colsample_bytree=0.5)

models={
    "Random Forest" : model1,
    "Gradient Boosting" : model2,
    "XG Boosting" : model3
}

In [86]:
#Model Building, Training and Evaluation
for name,model in models.items():
    mo=model

    #Training the model
    mo.fit(X_train,y_train)

    #Evaluating the model
    y_train_pred=mo.predict(X_train)
    mse1,mae1,rmse1,score1=evaluate_model(y_train,y_train_pred)
    y_test_pred=mo.predict(X_test)
    mse2,mae2,rmse2,score2=evaluate_model(y_test,y_test_pred)

    #Printing the model metrics
    print("="*30)
    print("Model : "+name)
    print("-"*30)
    print("Training Data :")
    print("Accuracy : ",score1)
    print("Mean Squared Error : ",mse1)
    print("Mean Absolute Error : ",mae1)
    print("Root Mean Squared Error : ",rmse1)
    print("-"*30)
    print("Testing Data :")
    print("Accuracy : ",score2)
    print("Mean Squared Error : ",mse2)
    print("Mean Absolute Error : ",mae2)
    print("Root Mean Squared Error : ",rmse2)
    print("="*30)
    print("\n\n\n")

==============================
Model : Random Forest
------------------------------
Training Data :
Accuracy :  0.9326564903393268
Mean Squared Error :  9670319866.76582
Mean Absolute Error :  52576.1559568629
Root Mean Squared Error :  98337.78453252757
------------------------------
Testing Data :
Accuracy :  0.812277834137626
Mean Squared Error :  21469534624.568684
Mean Absolute Error :  88545.94220490157
Root Mean Squared Error :  146524.86009059584
==============================




==============================
Model : Gradient Boosting
------------------------------
Training Data :
Accuracy :  0.970721511736131
Mean Squared Error :  4204300431.5277715
Mean Absolute Error :  46899.498298471604
Root Mean Squared Error :  64840.577044993755
------------------------------
Testing Data :
Accuracy :  0.8663403836004384
Mean Squared Error :  15286472692.3126
Mean Absolute Error :  73406.14930105624
Root Mean Squared Error :  123638.47577640465
==============================




==============================
Model : XG Boosting
------------------------------
Training Data :
Accuracy :  0.9444630146026611
Mean Squared Error :  7974942208.0
Mean Absolute Error :  61848.8359375
Root Mean Squared Error :  89302.53125
------------------------------
Testing Data :
Accuracy :  0.8654305934906006
Mean Squared Error :  15390521344.0
Mean Absolute Error :  75957.65625
Root Mean Squared Error :  124058.5390625
==============================

In [87]:
import joblib
joblib.dump(scalar,"Scalar.pkl")

['Scalar.pkl']

In [88]:
joblib.dump(model1,"RandomForest.pkl")

['RandomForest.pkl']

In [89]:
joblib.dump(model1,"GradientBoost.pkl")

['GradientBoost.pkl']

In [90]:
joblib.dump(model1,"XGBoost.pkl")

['XGBoost.pkl']